# Generated by Django 3.2.4 on 2021-07-03 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jaguarete_App', '0004_auto_20210702_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Jaguarete_App.categoria'),
        ),
    ]
