# Generated by Django 3.2.4 on 2021-07-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jaguarete_App', '0007_carrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
